### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by ghost** [ScottBrenner/hqtrackbot#1]
https://www.youtube.com/watch?v=Z_BpEL1IDr4

**Comment by ghost** [comment]
@ScottBrenner can you please reopen

here is some more context

https://redd.it/amlwde

bot is linking to totally different song

**Comment by ScottBrenner** [comment]
Thanks for the context, I am aware that the bot sometimes links to incorrect songs.

Please "downvote" these incorrect comments, they will automatically be deleted.

**Comment by ghost** [comment]
@ScottBrenner well, i guess we have 2 problems then

i downvoted 2 weeks ago and it still remains

**Comment by ScottBrenner** [comment]
Comments with score below `-1` are automatically deleted, may change to `0`.

**Comment by ghost** [comment]
@ScottBrenner please note that i have reported the bot based on your comments here.
