### ISSUE TITLE
Unavailable video

### ISSUE THREAD

**Issue by klaytoncavalcante** [ScottBrenner/hqtrackbot#2]
The bot posted an unavailable video.
Original video: https://www.youtube.com/watch?v=dHLOhdyDhYc
Bot suggestion: https://www.youtube.com/watch?v=VqdLnrcK4E8
Comment: https://www.reddit.com/r/Music/comments/ansk6t/diabulus_in_musica_healing_symphonic_metal_2014/efvn37d/

**Comment by ScottBrenner** [comment]
I'm able to view the bot's suggestion, guessing it's region blocked for you.
